# --------------------------------------------------------------------------
# версия kivi
#:kivy 2.0.0
# импорт hex цветов
#:import hex kivy.utils.get_color_from_hex
# --------------------------------------------------------------------------
# Описываем класс class Main(BoxLayout) для файла applink.py
<Main>:
    # ----------------------------------------------------------------------
    # параметры конструктора class Main(BoxLayout)
    orientation: 'vertical'
    # ----------------------------------------------------------------------
    LabelProgram:
        id: label_program
        text: 'ВВЕДИТЕ ИМЯ ПРОГРАММЫ:'
    # ---------------------------------------------------------------------- 
    TextInputFile:
        id: text_input_file
    # ---------------------------------------------------------------------- 
    ButtonMain:
        id: button_main_getPackageName
        text: 'getPackageName()'
        on_release: root.getPackageName()
    # ----------------------------------------------------------------------  
    ButtonMain:
        id: button_main_get_SDK_INT
        text: 'get_SDK_INT()'
        on_release: root.get_SDK_INT()
    # ----------------------------------------------------------------------   
    ButtonMain:
        id: button_main_getInstallerPackageName
        text: 'getInstallerPackageName()'
        on_release: root.getInstallerPackageName()
    # ---------------------------------------------------------------------- 
    # ScrollView - прокрутка текста
    BoxLayout:
        orientation: 'horizontal'
        BoxLayout:
            orientation: 'vertical'
            ScrollViewMain:
                LabelMain:
                    id: label_main
                    text: ''.join([(str(i) + '\n') for i in range(100)])
    # ----------------------------------------------------------------------

# --------------------------------------------------------------------------
# декорируемые классы:
# --------------------------------------------------------------------------
# ButtonMain - общие свойства кнопокок программы
<ButtonMain@Button>:
    # параметры текста
    font_size: dp(14)
    bold: True
    # автоматически переносить/растягивать текст внутри кнопки
    text_size: self.size
    # выравнивание текста внутри кнопки
    halign: 'center'
    valign: 'middle'
    # располодение кнопки в макете
    # pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    # размер кнопки относительно макета
    # size_hint: (0.3, 0.1)
    size_hint: (1.0, 0.15)
# --------------------------------------------------------------------------
# ScrollViewMain - общие свойства прокрутки текста (этикеток) программы
<ScrollViewMain@ScrollView>:
    do_scroll_x: False
    do_scroll_y: True
# --------------------------------------------------------------------------
# LabelMain - общие свойства текста (этикеток) программы
<LabelMain@Label>:
    # цвет текста
    color: "white"
    # автоматически переносить/растягивать текст
    text_size: self.size
    halign: 'left'
    valign: 'top'
    # пролистывание текста
    size_hint_y: None
    height: self.texture_size[1]
    text_size: self.width, None
    padding: 10, 10
# --------------------------------------------------------------------------
# LabelFile - общие свойства прокрутки текста (этикеток) программы
<LabelProgram@Label>:
    # цвет текста
    color: "white"
    # автоматически переносить/растягивать текст
    text_size: self.size
    halign: 'center'
    valign: 'center'
    # размер виджета
    size_hint: (1.0, 0.15)
    # стиль текста жирный
    bold: True
    # размер текста
    font_size: dp(14)
# --------------------------------------------------------------------------
# TextInputFile - общие свойства текстового поля ввода ИМЕНИ ФАЙЛА программы
<TextInputFile@TextInput>:
    # многострочный ввод
    multiline: False
    # запрет копирования текста
    allow_copy: False
    # блокируеи TextInput (True - Да, False - Нет)
    disabled: False
    # параметры текста
    # font_size: dp(15) # not work
    font_size: '15sp'
    bold: True
    # размер виджета
    size_hint: (1.0, 0.15)
    # выравнивание текста по центру
    halign: 'center'
# --------------------------------------------------------------------------
